= CloudSim Plus: A Modern, Full-Featured, Highly Extensible and Easier-to-Use Tool for Modeling and Simulation of Cloud Computing Infrastructures and Services.
:homepage: http://cloudsimplus.org
:imagesdir: images

_Manoel C. Silva Filho^1,2^; Raysa L. Oliveira^2^; Claudio C. Monteiro^1^; Pedro R. M. Inácio^2^; Mário M. Freire^2^_

_^1^Departamento de Informática - http://www.ifto.edu.br[Instituto Federal de Educação do Tocantins (IFTO)]_. _^2^http://www.it.pt[Instituto de Telecomunicações (IT)] and http://di.ubi.pt[Departamento de Informática], http://www.ubi.pt[Universidade da Beira Interior (UBI)]._

Cloud computing is a technology used everywhere, without users not even realizing. Companies usually rely on it to provide services accessible through the Internet. It is based on the same principles of utility services delivery such as water, electricity, gas and telephone, which are provided on demand and in a pay-per-use model. Such a technology has leveraged innovation in different economic sectors and encouraged entrepreneurship by enabling companies to quickly provide online services without the upfront costs of IT equipment acquisition. 

The cloud is compounded of multiple sets of highly-powerful computers, connected thought the Internet and distributed all around the globe. These sets are called data centers and each computer is called a server. A cloud provider is one having the main role of owning multiple data centers to provide cloud computing services. This groundbreaking technology is result of academic and industry research. 

Considering the high dimension, complexity and inherent costs of using a cloud infrastructure, research is frequently carried on through simulation environments. Simulation is a common practice in different study fields. They enable a system, such as a car manufacturer production line, to be modeled in a reduced and controlled environment, mimicking the behavior of that system. This way, the system can be studied to detect issues, areas to be improved and to envision possible solutions.

In this sense, CloudSim Plus is an open source, state-of-the-art cloud simulation software which allows modeling and simulation of cloud computing infrastructures. It is based on the most recent technologies, programming languages and tools, applying several software quality practices and methodologies to provide a tool for scientific research with industry-standard quality. 

CloudSim Plus has an extensive list of features which are described in the official website, enabling modeling and simulation of:

- cloud computing physical and logical infrastructures, including servers, network connections and services; 
- cloud customers and their cloud hosted services;
- end-users and load their access to hosted services imposing on computing resources.

The tool has built-in monitoring features, allowing a researcher to keep track of simulation execution, investigate issues and collect scientific data to guide the development of potential solutions. It also allows implementation and assessment of different policies for management of cloud computing resources, aiming to meet provider, customers and end-users' goals, such as:

- reduction of energy consumption, carbon emissions and financial costs for providers;
- optimization of computing resource usages to avoid both resource wastage and overbooking;
- quality of service assurance for customers.

The efforts on developing CloudSim Plus have been recognized by the EUBrasilCloudForum and partial results from the research behind it were published on the IFIP/IEEE International Symposium on Integrated Network Management.